### ISSUE TITLE
Door position does not decrease when closing

### ISSUE THREAD

**Issue by chrispatin** [PaulWieland/ratgdo#10]
Hi Paul,

After connecting the board the commands work without no issues. Also the status appears to show the correct results when opening.

However when closing, the door position does not appear to decrement much. Bad connection on RPM1 or RPM2? The garage door appears to operate without issues.

I have attached a serial log. First the door was opened, then it was closed

[serial.log](https://github.com/PaulWieland/ratgdo/files/9740541/serial.log)

**Comment by chrispatin** [comment]
I see there is another issue with inconsistent behavior with statuses on door closes.

The sticker on the opener shows part number 050ACTWF

**Comment by chrispatin** [comment]
Duplicate - #2

**Comment by PaulWieland** [comment]
This seems to be pretty common and I think I can fix it with a software update.
