### ISSUE TITLE
MQTT vs ESPHome

### ISSUE THREAD

**Issue by Ch0rchie** [PaulWieland/ratgdo#102]
Hi, what are your thoughts on RatGDO using MQTT vs. ESPHome? I already have other devices in ESP and haven't used MQTT yet, but wanted to see if there are any issues using ESPhome.

Thank you!!!

**Comment by PaulWieland** [comment]
Theres nothing wrong with ESPHome, use that if you prefer.

**Comment by Ch0rchie** [comment]
Thanks so much! I set up my ESP8266 today, just waiting on the shield. Do you have an estimate when orders from October will ship? Thanks!!

**Comment by PaulWieland** [comment]
As long as nothing goes wrong, I should have all backorders shipped by the end of the month.

**Comment by Ch0rchie** [comment]
Hi, just checking in to see if you have any updates on backorders? And for my shield order, will you be sending the v2.0 or 2.5?

Thank you! I am excited to get this installed!
