### ISSUE TITLE
Confused about wiring instructions 

### ISSUE THREAD

**Issue by vamichael** [PaulWieland/ratgdo#107]
On [this page](https://paulwieland.github.io/ratgdo/03_wiring.html), it says you only need three wires (besides power) to be connected to the shield.

However, [this page ](https://user-images.githubusercontent.com/4663918/217019759-a3fdc892-a104-44d3-bdf0-4fcb058cfe35.png) says you need five (excluding power).  What’s the difference between the two instructions?

**Comment by PaulWieland** [comment]
V2 boards only require 3 wires. Red / Control, White / Ground and Black / Obstruction.
