### ISSUE TITLE
Work with Liftmaster ML800EV

### ISSUE THREAD

**Issue by dermm** [PaulWieland/ratgdo#108]
Hello,
I just received my Ratgdo and tried it directly.

However, my GDO does not seem to work.
The obstacle detection works but nothing else.
No status and no open / close possible.
The ESPHome version sends a notification about an error in communication when starting.
I have tested both the normal MQTT SW and the ESPHome.

My GDO has a yellow round learn button.

What could be wrong?
Wiring:
![photo_2023-10-09_16-17-02](https://github.com/PaulWieland/ratgdo/assets/17449533/de41e3ca-5e0f-4398-8d7a-28cf75e2a097)

**Comment by PaulWieland** [comment]
I see two extra wires connected to the white and gray terminals on the GDO. I assume you have those wired to `wht/gnd` & `blk/obst` terminals on the shield? Where's the red/ctrl wire?

**Comment by dermm** [comment]
The shield is connected via the Red/white/Black wire (Pos. 1 Red,2 White,3 Gray). 
On 2 and 3 is the obstacle detection connected.

**Comment by limwakra** [comment]
Got the same motor here in the Netherlands, use the #0(green) for the red wire and don't use the red port. Got it working today.

**Comment by dermm** [comment]
> Got the same motor here in the Netherlands, use the #0(green) for the red wire and don't use the red port. Got it working today.

Thank you very much, that was the trick!
