### ISSUE TITLE
8550W Support

### ISSUE THREAD

**Issue by evanbills** [PaulWieland/ratgdo#109]
First off:  thank you so much for creating this product and project! 

I have a LM 8550W that I've connected up (photo attached).  I've also flashed v2.24a onto my v2.0 board recently ordered and received from you.  Controls don't seem to work at all, but I do get status updates (heartbeat?) on the MQ.

I'm guessing this is a Sec 1.0 opener, or hybrid, so I am not sure this will work but I wanted to try. (I was tired of getting ads in the Liftmaster app)

Please let me know if I have missed a configuration or if there is anything I can supply to assist troubleshooting.

![image](https://github.com/PaulWieland/ratgdo/assets/4141051/f0e32e99-10f4-481e-be39-0aa9d16b4eaf)
![image](https://github.com/PaulWieland/ratgdo/assets/4141051/e7461e72-536c-47f4-98ee-1c50736634aa)

**Comment by PaulWieland** [comment]
Two things are wrong:

- You're using beta firmware. Please install v2.1
- The board is wired to the GDO incorrectly. Please check the wiring diagram/silkscreen on the back of the board

**Comment by evanbills** [comment]
That did the trick!  Apologies, Paul.  I was following the wiring diagram [here](https://user-images.githubusercontent.com/4663918/235453980-04a642fa-a181-4297-b4f3-06e1315e02fa.png) vs. what's actually printed on the board :facepalm: .  

I can report that this works great with the 8550W.  Thank you again!

**Comment by PaulWieland** [comment]
Thats the correct wiring diagram. It shows the back of the board (as indicated by the QR code and silk screen labels). Glad you got it working.
