### ISSUE TITLE
Back order for bare shield?

### ISSUE THREAD

**Issue by aufflick** [PaulWieland/ratgdo#115]
Another myQ refugee here :) I have a drawer full of D1 8266 boards so I'd love to buy the bare shield. Is there a list to join to get notified when you plan to start allowing orders of the bare shield again? I don't mind waiting but I'd hate to miss any pre-orders :)

**Comment by PaulWieland** [comment]
Hi @aufflick you can order a bare shield from the main page: http://paulwieland.github.io/ratgdo/ 
I will take the backlog off once I'm caught up, which should hopefully be by the end of this month.
