### ISSUE TITLE
Stuck on Preparing Installation

### ISSUE THREAD

**Issue by shinjestari** [PaulWieland/ratgdo#120]
I am trying to install the initial ESPhome for ratgdo and it is failing to initialize. I have tried resetting the device and changed cables and PCs and i am still getting the same error. 

![image](https://github.com/PaulWieland/ratgdo/assets/45239833/beb6ca4e-0404-474c-928d-63b6d1398b86)

**Comment by shinjestari** [comment]
The device is broken. It fails to turn on correctly. Got a new one from Amazon and it loaded up correctly.

**Comment by rroller** [comment]
I had this same issue. Seems to work with a new USB cable.
