### ISSUE TITLE
Collision detected issue

### ISSUE THREAD

**Issue by Totemus** [PaulWieland/ratgdo#124]
ESP Newby here. After flashing the board, I visit the device that shows eternal "Collision detected, waiting to send packets". When added to Home Assistant Obstruction sensor = Clear. The board can't operate the opener. Another ratgdo board connected to another opener works flawlessly, so I'm sure I wired the boards correctly.

**Comment by J-Pipe** [comment]
Also seeing this when I flashed using the ESPHome flasher here: https://ratgdo.github.io/esphome-ratgdo/. I have not yet wired anything to the garage door opener yet.

**Comment by J-Pipe** [comment]
Looks like I'm seeing this because I haven't hooked it up yet.
https://github.com/ratgdo/esphome-ratgdo/issues/47#issuecomment-1722371519

**Comment by J-Pipe** [comment]
Actually, hooked it up today and still seeing the issue and nothing is working. Hmmmm.

**Comment by Totemus** [comment]
> Looks like I'm seeing this because I haven't hooked it up yet.
> 
> https://github.com/ratgdo/esphome-ratgdo/issues/47#issuecomment-1722371519

Confirmed. Operator mistake.
