### ISSUE TITLE
Shipping to Canada

### ISSUE THREAD

**Issue by andornaut** [PaulWieland/ratgdo#135]
[The website](https://paulwieland.github.io/ratgdo/) mentions that shipping to Canada is available:
> ratgdo shields available to order Shields are available and shipping domestic USA via USPS. Shipping to Canada is also available, but costs $14.

When [checking out on Square](https://checkout.square.site/buy/X3QUEQGEQG4I6B24NC7EBHL3), however, Canada doesn't appear to be a supported shipping destination:
> This Address is not supported, please select another

![canada](https://github.com/PaulWieland/ratgdo/assets/737842/b3d3c8fa-a670-4c7b-b2e1-afc5ccc9f99f)

It'd be great if shipping to Canada was offered!

**Comment by Imitationman** [comment]
I don't think its the Canadian address that is the problem. I tried to place an order to Texas this evening and I get the same error that my address is not supported by Square. I think this is a Square issue.

**Comment by PaulWieland** [comment]
Yes it is. I'm trying to figure out what is wrong. Their store management software is something else...

**Comment by PaulWieland** [comment]
I think I have it fixed, please try again!

**Comment by andornaut** [comment]
Worked. Thanks!
