### ISSUE TITLE
GDO Master / Temp Codes

### ISSUE THREAD

**Issue by naeemu** [PaulWieland/ratgdo#140]
I have a keypad outside which has temporary codes for dog sitters and such. This is the only entry point which still requires manual intervention to enable/disable codes.

@PaulWieland have you come across anything which may potentially allow ratgdo to be able to enable/disable temporary codes from another remote? Now that I am writing this out, perhaps those codes only live on that specific keypad and have nothing to do with the GDO. The lights on the GDO blink specific times to confirm the codes - which still doesn't mean that the codes have anything to do with the GDO.

Figured I'd write this out if you had any thoughts on this - or for someone else thinks of this.

**Comment by PaulWieland** [comment]
The outdoor keypads are wireless. The lock command that ratgdo can send to the gdo locks out wireless remotes. It should lock out the keypad too. 

It may not be exactly what you are looking for but you could setup an automation that locks out the wireless remotes after a certain sequence of events/times of day/etc.
