### ISSUE TITLE
Web Installer Help

### ISSUE THREAD

**Issue by raf63086** [PaulWieland/ratgdo#149]
I am having trouble using the ratgdo esp web installer.  My computer seems to recognize there is a device and I have confirmed I am using a data cable and not a power only USB cable.   When I click 'Connect' on the web installer I am able to select the port, go through the menus to install ratgdo, and confirm installation, however the installation fails with the error:

'Failed to initialize.  Try resetting your device or holding the BOOT button while clicking INSTALL.'

I have a v2.0 board.  Tried using both Microsoft Edge and Google Chrome.  No lights come up on the board, I'm not sure if it is supposed to.  Also attempted to use the ESPHome port installer and got a similar error.  Also tried to install on a Mac laptop but got the same error there as well.

Any troubleshooting suggestions would be appreciated.

![InstallFail](https://github.com/PaulWieland/ratgdo/assets/138953815/87b07677-c733-4fea-92da-bff949822eec)

**Comment by PaulWieland** [comment]
whats your email address or order number?

**Comment by raf63086** [comment]
I believe it is 11ee5e5687b950189b78ac1f6bbbcc9c

**Comment by PaulWieland** [comment]
Send an email to ratgdo@gmail.com
