### ISSUE TITLE
Backorder model fulfillment 

### ISSUE THREAD

**Issue by mattvirlee** [PaulWieland/ratgdo#152]
Hey Paul - ordered a pair of the boards a week or so ago. I’ve got Security 1 garage door openers, so I’m hoping I’ll receive the v2.5 boards when they ship. 

Will backorders be fulfilled with v2.5 boards going forward?

**Comment by PaulWieland** [comment]
Hi Matt, yes you will receive v2.5 boards

**Comment by mattvirlee** [comment]
Excellent! Can't wait. Closing Issue.
