### ISSUE TITLE
When are we expecting new 2.5 orders to ship?

### ISSUE THREAD

**Issue by chilman408** [PaulWieland/ratgdo#153]
Hello,

Hate to add this as a github issue but I can't find any contact for order support.

The order page just says this is on back order.  About how long of a wait for these back orders are we talking about?

**Comment by TopBanana123** [comment]
Following, just ordered! 

Probably sooner than my junk MyQ API key starts working

**Comment by Kaldek** [comment]
Link to DIY basic shield if you can't wait:
https://github.com/Kaldek/rat-ratgdo

**Comment by PaulWieland** [comment]
Hi there, you should have gotten an email with an order status update. Lead times have gone from 6 weeks to 3 weeks and keep improving. I hope to be back to same day shipping soon.
