### ISSUE TITLE
Possible to control connected gate opener?

### ISSUE THREAD

**Issue by TopBanana123** [PaulWieland/ratgdo#154]
I have a MyQ Opener which is connected to WiFi, and my LA400 gate opener is connected to the garage door opener, which then lets me control both via the Garage Door Opener/App

Is there any possibility for the Ratgdo to also control the already connected gate opener?

**Comment by PaulWieland** [comment]
No confirmations yet, but there are several already open issues about interfacing with gate openers. It seems as though there is a serial interface on at least some of the gate controllers. Others seem to have limit switches and dry contact control which would also work (just requires an extra wire).

**Comment by TopBanana123** [comment]
> No confirmations yet, but there are several already open issues about interfacing with gate openers. It seems as though there is a serial interface on at least some of the gate controllers. Others seem to have limit switches and dry contact control which would also work (just requires an extra wire).

Thanks. If using the dry contact control or SBC, I assume we would have to figure out another way to have the gate open status?

**Comment by PaulWieland** [comment]
Duplicate #90
