### ISSUE TITLE
MQTT Request Status

### ISSUE THREAD

**Issue by AryasDad** [PaulWieland/ratgdo#158]
Just ordered and am investigating how to handle one of my needs. I have a digital dashboard that intercepts MQTT messages to post up if garage doors are open or closed. 

Looking at the MQTT commands it does not appear that you can request current status. The status updates appear to only send when the activity occurs. 

For my dashboard it may have an update and gets rebooted and will not have the current status until something happens. So my request is can it be added to introduce a status request so the ratgdo would send out a current status?

Thanks!

**Comment by PaulWieland** [comment]
That's one of my favorite things about MQTT... the messages can be retained. 

Here's what happens when I subscribe to the status topic on my phone:
![image](https://github.com/PaulWieland/ratgdo/assets/4663918/4492aab8-d906-420d-9caf-edc7080e5db5)
