### ISSUE TITLE
Backorder update 

### ISSUE THREAD

**Issue by mclausha1** [PaulWieland/ratgdo#160]
Hello, I am looking to place a order for a complete kit and before I do I was wondering what the time frame for shipping as I don't wish to end up becoming one of those types that constantly ask where there product is. I understand it may be a few weeks if anything but couldn't seem to find a lead time posted anywhere. Thank you for putting this product out and basically creating not only a workaround but a way for us to give myq the middle finger since it don't want to play ball with home assistant.

**Comment by PaulWieland** [comment]
Hi @mclausha1  orders received today should ship in 2-3 weeks.
