### ISSUE TITLE
Ratdgo esp web installer issue

### ISSUE THREAD

**Issue by dmoraca** [PaulWieland/ratgdo#163]
Hello
I recently purchased two of the same ratgdo shield with ESP8266 D1 Clone, they arrived very quickly.
I am now trying to install ratdgo v2.1 using web installer (https://paulwieland.github.io/ratgdo/flash.html). One of them worked immediately but the second one has an issue.
see below screen shots, so I am hopping someone can help.

Thank you in advance
![image](https://github.com/PaulWieland/ratgdo/assets/116373801/7874e7a2-7312-4c51-83d2-ea4b47be3884)
![image](https://github.com/PaulWieland/ratgdo/assets/116373801/08aca16c-dd75-43d2-a37e-e5743b1bcaa2)
![image](https://github.com/PaulWieland/ratgdo/assets/116373801/d128ec79-1212-4f11-8b2d-5913e0cecde7)
![image](https://github.com/PaulWieland/ratgdo/assets/116373801/fb0eb7d8-effe-44e2-be88-a06fb8bf0956)
![image](https://github.com/PaulWieland/ratgdo/assets/116373801/52817057-b949-41c8-a94a-d6c5add4e4d1)
![image](https://github.com/PaulWieland/ratgdo/assets/116373801/7d76e997-bf74-4592-9e55-caae0215917c)

**Comment by PaulWieland** [comment]
Hi, can you please email ratgdo@gmail.com using the same email address that you ordered with.
Thank you.
