### ISSUE TITLE
Contact Information

### ISSUE THREAD

**Issue by yjamal01** [PaulWieland/ratgdo#164]
Apologies for posting here but I feel like I have exhausted all other options of communication 

I am trying to make contact regarding my order, however emails to have gone unanswered. 

I tried to find another method of communication but had no luck. Hoping that by posting here I can get the developers attention and my issue can be resolved. 

TIA and AFI

**Comment by PaulWieland** [comment]
What is your email address?

**Comment by yjamal01** [comment]
yaqz101@gmail.com

thank you and apologies again
