### ISSUE TITLE
Upgrade?

### ISSUE THREAD

**Issue by borski** [PaulWieland/ratgdo#170]
I'm certain the answer to this is no, but is there anything _meaningfully_ different between 2.0 and 2.5? I bought the shield literally a month ago, got it all set up in a jiffy, and it works fine - is there any reason to upgrade to the 2.5 board, which includes the ESP8266 or are they the same, featurewise, for my situation?

**Comment by PaulWieland** [comment]
If you have a security + 2.0 opener, there is no reason for you to upgrade to v2.5.
