### ISSUE TITLE
Collision Detected

### ISSUE THREAD

**Issue by chernerd** [PaulWieland/ratgdo#173]
After hooking everything up and loading esphome I am receiving an error in the esphome log. HA recognizes them and they appear under the ESPHome page and in the devices/entities.

`Collision detected, waiting to send packet`

I have double and triple checked my wiring and have been unable to fix the error. Attached are pictures of the wiring and garage door pieces.

![PXL_20231022_182615376](https://github.com/PaulWieland/ratgdo/assets/60118771/87e03e2e-45a4-4037-a9a7-fe894456c6df)
![PXL_20231021_232450145](https://github.com/PaulWieland/ratgdo/assets/60118771/73a00e8c-1ad8-4d38-b8a2-0502a7ee2628)
![PXL_20231022_182622869](https://github.com/PaulWieland/ratgdo/assets/60118771/d40e3b7b-7ee9-4ebd-9185-b7d068a7cb40)
![PXL_20231022_182608690](https://github.com/PaulWieland/ratgdo/assets/60118771/8452b9ac-78d3-41c1-8192-1ff6f37b8b39)
![PXL_20231031_171521861](https://github.com/PaulWieland/ratgdo/assets/60118771/2526add5-3f61-45fb-b058-14b25b5df54e)
![PXL_20231031_171618963](https://github.com/PaulWieland/ratgdo/assets/60118771/130f98fa-e575-4707-b9fd-5eb4e1e3f87d)

**Comment by PaulWieland** [comment]
What happens with the "OEM" MQTT firmware?

**Comment by chernerd** [comment]
I used a new esp board and flashed the OEM MQTT firmware. When I attached to the ratgdo I see it auto discovered in home assistant. None of the commands are working (up/down/light).

**Comment by PaulWieland** [comment]
Did the door and light respond on the esphome version? If so it’s a rolling code issue. try the 2.26a release of the mqtt version

**Comment by chernerd** [comment]
No, I haven't been able to get the door to respond on either version.

**Comment by PaulWieland** [comment]
Is the mqtt version saying that there’s an obstruction detected? 

Double check your ground connection (white terminal). You can also try the other ground terminal on the opposite side of the board. There should be continuity between both ground terminals, the gnd pin on the d1 and both white terminals on the gdo.

**Comment by chernerd** [comment]
It does say obstruction detected.

Do I have the d1 attached correctly? I'm using the connector in my picture above to attach the d1 to the gdo.

**Comment by PaulWieland** [comment]
It looks correct but I can’t see for sure which wire is in which terminal. 

Do you have a multimeter that you can check continuity with? I still think the ground isn’t connected because both the obstruction and gdo control are not working.

**Comment by chernerd** [comment]
What should I check with the multimeter?

With everything hooked up my garage door still works with the button.
Doesn't that mean the obstruction sensors are hooked up correctly/grounded?

I tried switching the ground to the other side of the gdo and am
still getting the same error.

**Comment by rlowens** [comment]
> What should I check with the multimeter?

Confirm continuity between the white terminals on the GDO and GND on the ratgdo (GND on D1 mini and GND on the terminal blocks).

**Comment by chernerd** [comment]
It doesn't have continuity. How am I supposed to be attaching the d1 to the
shield? I'm using my black pronged piece shown in my original post.

**Comment by rlowens** [comment]
Ah, I see the confusion. The "black pronged piece" is called a Pin Header and you need to solder the short end of the pins into your D1 Mini board like this:
![image](https://github.com/PaulWieland/ratgdo/assets/35885181/0fc675cd-92e2-49b6-b0e9-824d3ed94051)

Here's someone doing it on YouTube: https://www.youtube.com/watch?v=X7iBkSICqvQ

You can't just pin the D1 Mini to the ratgdo and get a good connection:
![image](https://github.com/PaulWieland/ratgdo/assets/35885181/5a9eaec1-55e2-4a49-833e-b61980f1756d)

I was going to suggest the possibility of purchasing a D1 Mini with the headers pre-installed, but 10 pages of Amazon didn't have any. Weird. The NodeMCU-style boards I use almost always come pre-soldered, but it looks like D1 Mini-style boards mostly don't.

**Comment by chernerd** [comment]
Thanks! I soldered the board this morning and was able to get everything
working. It should have been obvious that I needed to solder but because it
wasn't explicitly called out I never considered it (my fault).

**Comment by PaulWieland** [comment]
> Ah, I see the confusion.

Good eye. I totally missed it in the provided photo. Thank you for the help👍
