### ISSUE TITLE
Chamberlain  opener - how to wire

### ISSUE THREAD

**Issue by bstork0807** [PaulWieland/ratgdo#178]
I understand how to wire the side with obstacles and  control. Is it necessary to wire the trigger and status side? Do I need to put reed switches on the door to show status?

**Comment by PaulWieland** [comment]
Hi @bstork0807 what kind of chamberlain opener do you have? 
Is it security + 2.0, security + 1.0 or something older?

**Comment by bstork0807** [comment]
chamberlain WD1000WF with security + 2.0

**Comment by bstork0807** [comment]
Hey Paul   just wanted to touch base because I wanted to place an order if this will work for me.  opener is a 
chamberlain WD1000WF with security + 2.0

**Comment by PaulWieland** [comment]
Its a security + 2.0 opener, so yes its supported.

See here https://github.com/PaulWieland/ratgdo/wiki
And here https://paulwieland.github.io/ratgdo/03_wiring.html

**Comment by bstork0807** [comment]
Thanks Paul.. I guess my main question is.. Do I need to use any of connections i have marked in red?

![image](https://github.com/PaulWieland/ratgdo/assets/57011584/dc59c8df-df22-4616-9d34-8e9d9e24f562)
