### ISSUE TITLE
Wiring Question

### ISSUE THREAD

**Issue by griffisc306** [PaulWieland/ratgdo#189]
I feel dumb asking this but am a slight novice when it comes to wiring. I ordered v 2.5 and have a yellow button opener (not one of the exceptions listed) and am trying to prepare by looking at the diagrams and picture.  I got the kit with the 3 wires provided but am confused because the diagram makes it look like there are 2 wires coming from each sensor. I may have more info when I get the device but  am trying to figure out which wires go where specifically for the 2 obstruction pieces.

**Comment by PaulWieland** [comment]
There are two obstruction sensors. Both need power and ground from the GDO, so they are wired in parallel to white (gnd) and black (obst) terminals on the GDO.

You wire ratgdo in parallel with the sensors and wall panel. v2.5 includes a pass thru terminal for the obstruction sensor and wall panel so you dont have to try and put multiple wires in one terminal.

Hope this helps!

**Comment by griffisc306** [comment]
I believe that helps. So if I got  the kit with the included wires, I should not need any extra wires?  between the kit and the wires already in place I should have all I need?

**Comment by endquote** [comment]
Coming with the same question... I think the device will meet my needs, especially with the installation kit, but maybe I'm missing some installation instructions. Has anyone prepared detailed instructions with photos or video?
