### ISSUE TITLE
esp8266 with external antenna?

### ISSUE THREAD

**Issue by numindast** [PaulWieland/ratgdo#194]
Would love to know if you'd consider having a batch made with external antenna connectors on the esp8266 module. JLCPCB and PCBway both carry the parts.

My detached garage gets poor signal at times and this project piqued my curiosity.

Thx!

**Comment by samwiseg0** [comment]
You could always switch out the one that comes with the board with these that have the external antenna. They are relatively inexpensive. 

https://www.aliexpress.us/item/3256805747213255.html

**Comment by PaulWieland** [comment]
Lets see what the next version brings ;)
