### ISSUE TITLE
Request: Maintain up-to-date comparison of firmware options

### ISSUE THREAD

**Issue by agelwarg** [PaulWieland/ratgdo#196]
Trying to read through different GitHub issues on each project, I realize it’s a little difficult to know the current state of affairs / differences between running the two firmware choices. I see value in both projects being able to reference a similar matrix.  It seems like you have genuine interest in both being options/choices as I see your activity on the ESPhome side as well…do you think maintaining a simple comparison between the two would be helpful?  I wonder if others have similar questions about why to choose one over the other.  As one example, I’m not sure of the security+ 1.0 status on the ESPhome side.

**Comment by PaulWieland** [comment]
Yes I do think maintaining a feature matrix is necessary, but things have evolved quickly and I have been a little busy trying to keep up.

I just recently added the feature matrix to the website but it is only for explaining the differences between control protocols. I have a draft going which attempts to add the features from the other firmwares that are in development. 

https://paulwieland.github.io/ratgdo/01_features.html

**Comment by agelwarg** [comment]
Yep, I saw that matrix...it's great.  It's also part of the reason I thought of a firmware comparison matrix.  Not sure how I could help, but if I can, just let me know how.

**Comment by PaulWieland** [comment]
I just added the firmwares into the matrix. Its a little busy, but hopefully still readable.

**Comment by agelwarg** [comment]
I didn't think it was there when I first looked....and then it was.  Glad you said you "just added" because now I know I'm not crazy (at least in this case).

**Comment by agelwarg** [comment]
btw, the + is in the matrix legend as &plus;

![image](https://github.com/PaulWieland/ratgdo/assets/392423/51a74429-0b6b-41c9-9ccd-e9db674c27e1)

**Comment by PaulWieland** [comment]
Also fixed. Sometimes I really hate markdown.
