### ISSUE TITLE
Brand new 2.5 with printing upside down?

### ISSUE THREAD

**Issue by Ramias1** [PaulWieland/ratgdo#215]
Its too late tonight to test this, but I saw this thread:  https://community.home-assistant.io/t/ratgdo-getting-collision-detected-waiting-to-send-packet-many-times-per-second-in-log/628335/6 and then this comment: https://community.home-assistant.io/t/ratgdo-getting-collision-detected-waiting-to-send-packet-many-times-per-second-in-log/628335/9 

and found this diagram showing the wires to the left with USB on the bottom:

![](https://user-images.githubusercontent.com/4663918/276749741-fe82ea10-e8f4-41d6-872f-55eec88d2aab.png)

Here is a photo of mine; printing for wires to the left with power on the TOP

![IMG_2385](https://github.com/PaulWieland/ratgdo/assets/12807035/41acf533-05cb-44f4-83a2-eec10b9b8840)

Could my issues with Collision Detected be due to the soldering being upside down?  The photo is how my unit arrived.  Thanks

**Comment by PaulWieland** [comment]
The D1 mini is installed upside down. Pull it off the board, rotate it 180 degrees and you will be golden. If I sent it to you that way, I apologize!

**Comment by Ramias1** [comment]
Thanks.  Yeah it came this way.  I was about to say "it's soldered on" but alas... I was able to pull it right out :).  Will test first thing tomorrow.

**Comment by Ramias1** [comment]
Amazing how easy this was with the board orientation correct!
