### ISSUE TITLE
Order Status

### ISSUE THREAD

**Issue by madansu** [PaulWieland/ratgdo#217]
Hi there !

Is there any way I can get an order status ? 
I purchased two units (1x 2.0 and 1x 2.5) over 3 weeks ago, and I have had no information on either order since. 

Thanks,

**Comment by PaulWieland** [comment]
Look for an email later today

**Comment by DukeChocula** [comment]
Is this an everyone email with order updates, or specific to @madansu? Yesterday was the 3 week mark for me.
