### ISSUE TITLE
No control for liftmaster 8500

### ISSUE THREAD

**Issue by SaurabhK0001** [PaulWieland/ratgdo#220]
Connected ratgdo 2.5 with ESPHome firmware to my garage door opener, I have no control (door open / close, light etc) from the device interface or home assistant. The status also does not update.

Attached wiring screenshots 
![Screenshot 2023-11-10 at 4 31 33 PM](https://github.com/PaulWieland/ratgdo/assets/34254842/2c7227e5-ac21-48ad-b254-1120d232ce2c)
![IMG_8206](https://github.com/PaulWieland/ratgdo/assets/34254842/d863f564-c8bc-4fe3-9022-df7e7527af87)
![IMG_8208](https://github.com/PaulWieland/ratgdo/assets/34254842/4e56d2e9-dceb-47b8-994b-276f05e82b92)
![IMG_8213](https://github.com/PaulWieland/ratgdo/assets/34254842/43379a75-23cf-4188-80f0-93b00bb3a127)

**Comment by PaulWieland** [comment]
See here: https://github.com/PaulWieland/ratgdo/wiki
You need security + 1.0 control protocol which isn't yet supported by the ESP Home firmware.

[From the feature matrix](https://paulwieland.github.io/ratgdo/01_features.html):
<img width="540" alt="image" src="https://github.com/PaulWieland/ratgdo/assets/4663918/362346ad-aed3-4a6b-bc27-240540da4ad1">

**Comment by SaurabhK0001** [comment]
I’ll try with the Mqtt firmware. The manual for the gdo mentions security +2.0 (attached)

Thanks,
Saurabh

**Comment by PaulWieland** [comment]
﻿It’s one of the few transition models. It uses sec+2 wireless but sec+1 wireline control.

**Comment by SaurabhK0001** [comment]
Thanks, yes it worked with MQTT when I switched protocol to 1.0. Might be helpful if this information in searchable

Thanks,
Saurabh
