### ISSUE TITLE
OTA Updateb

### ISSUE THREAD

**Issue by tannerwastaken** [PaulWieland/ratgdo#235]
Hello! I got everything setup and wired properly… the only thing is I forgot to include a username and password during the configuration and MQTT doesn’t allow anonymous logins. So how can I access/update the ratgdo with an OTA? Is there a portal or something? I tried accessing the local IP the board is assigned to and nada. Thank you!

**Comment by PaulWieland** [comment]
Please resubmit your request with the new issue template filled out.
