### ISSUE TITLE
Ordered Kit - Wrong Address

### ISSUE THREAD

**Issue by DougEubanks** [PaulWieland/ratgdo#237]
When I ordered the kit, I selected Google Pay, which never allowed me to verify the shipping address.  It defaulted to an address I hadn't lived at in over a decade and completed the checkout.  I can't find any order support contact information, likely on purpose to keep the "where's my order" and "when backorder" chatter down.  I don't know how else to contact you besides the suggested bug report.

My order number is 1132407739, can someone reach out to the email address on the order so we can get this updated?  The phone number is old too and not mine anymore.

**Comment by mattvirlee** [comment]
Reply to the order confirmation email you got with this information.
