### ISSUE TITLE
Received only payment receipt - no order confirmation email sent

### ISSUE THREAD

**Issue by scooterusa** [PaulWieland/ratgdo#239]
I placed an order on October 31st but never received a confirmation email with an order number.

I also checked my spam folders and all other folders. So I didn't miss it if it got sent. I waited a little bit before reaching out here in case the order confirmation email got delayed a little 

Who do I contact to have the order confirmation sent, or how can I have it sent?

Replying to the email in the payment receipt does not work, and I see no contact information I can use for this purpose.

**Comment by PaulWieland** [comment]
Please reply to your square receipt

**Comment by scooterusa** [comment]
Just did... Hopefully this time it works.

**Comment by PaulWieland** [comment]
I didn’t receive anything. Send an email to ***@***.***

**Comment by scooterusa** [comment]
I just sent it again and made absolutely sure it was sent to an email address. I used the one that shows up when I go to reply to the payment receipt email. For good measures I sent it twice... One from the email address that I used when placing the order, and again from my personal domain name.

Email address after the @ is "reply2.squareup.com"

**Comment by donavanbecker** [comment]
I have tried to email the receipt directly also and no response.

**Comment by wastingaeons** [comment]
experiencing this as well

**Comment by scooterusa** [comment]
Just wanted to see if you got my yet PaulWieland. 

Thanks for helping me with getting the order confirmation receipt sent again.

**Comment by donavanbecker** [comment]
> I have tried to email the receipt directly also and no response.

got my update email today. but no response.
