### ISSUE TITLE
Documentation: Soldering locations for 45ACCL1 Rev C

### ISSUE THREAD

**Issue by antsar** [PaulWieland/ratgdo#25]
This board has a slightly different layout from the one in the docs. Maybe it would be helpful to document soldering locations for various boards? Here's a photo of the pins that worked for me.

![45ACCL1](https://user-images.githubusercontent.com/2976310/210608995-0f9814d4-0a85-490e-a789-d82b68cb7b88.jpg)

(The Obst/Gnd/Ctrl lines are available as Red/White/Black terminals too. I just preferred to keep everything inside the opener.)

**Comment by PaulWieland** [comment]
Added to https://paulwieland.github.io/ratgdo/03_wiring_soldered.html
Thank you for the contribution!
