### ISSUE TITLE
Shield Schematics / Shipping outside of USA

### ISSUE THREAD

**Issue by dorkage** [PaulWieland/ratgdo#26]
I would love to buy the Shield Paul has setup for this project, but it is prohibitively expensive to get shipped to Canada.

I can see some passive components as well as a transistor on the shield in some photos. Is if possible to get a schematic so I can add the correct component to my bare ESP setup I am making?

**Comment by Buzzzsaw** [comment]
I would be interested as well, as I might even have the components lying around already.

**Comment by mattthhdp** [comment]
+1 and I really don't mind if you add an option like 5,10 buck to dl the schematic or something like that.
I live in Quebec and the shipping is almost double the price of the product.
