### ISSUE TITLE
Soldering locations for 45DCBL5A

### ISSUE THREAD

**Issue by ebruchez** [PaulWieland/ratgdo#30]
This is an older board from 2011. I just took pictures and it seems that most locations are similar to 45ACCL1, but I don't know about the RPM1 and RPM2 lines. I didn't take the board out to take this picture so the quality is not great but I wonder if there is a quick way to figure it out!

![848D6B6D-B9C4-47BC-8902-9BD11B1CACD6](https://user-images.githubusercontent.com/105769/218353334-f8869c0d-2fd1-4d6c-8454-cd158a24ce20.JPG)

**Comment by PaulWieland** [comment]
Version 2.0 boards eliminate the need for soldering.

Version 1.0 boards are incompatible with 2.0 firmware unless you solder a transistor to the board. I will send anyone with a 1.0 board a free transistor if they email me their order number. Instructions for the mod are forthcoming.
