### ISSUE TITLE
Convert v1 board to v2

### ISSUE THREAD

**Issue by rafaelmathieu** [PaulWieland/ratgdo#32]
I recently bought a v1 board and never got around to installing it. I saw that a v2 was now available. Anyway way to convert it to v2?

**Comment by abishur** [comment]
Here's the instructions I got for doing this and it worked for me.
You will need a mosfet with a gate threshold of >2, I used the 2n7000

Then connect:

source to ground
Gate to Red/gdo signal
Drain to RMP2

![20230505_103225](https://github.com/PaulWieland/ratgdo/assets/1671047/75e2debc-3f2b-41c2-8ebe-47faa4736f14)

That's how I had it wired to the back and I affixed the mosfet under my ESP with some tape I use on circuit boards 

![20230505_103219](https://github.com/PaulWieland/ratgdo/assets/1671047/4718dc5e-f99b-45e5-bd15-ee4181cf740e)

Then I placed it inside the garage door housing affixing it with some 3M tape, but in hindsight this means when I want to do a firmware update I need to open up my garage door unless OTA works?

![20230513_170154](https://github.com/PaulWieland/ratgdo/assets/1671047/22fe345c-bc74-49da-aba2-e431cd0e3130)

Regardless I followed the soldering method for my garage door revision and it works just fine.  I am have some odd disconnect issues, but I think those are resolved in v2.1

**Comment by PaulWieland** [comment]
Here's my install of a retrofitted 1.0 board. It's critical to use a mosfet with a gate threshold slightly more than 2v.

![IMG_6017](https://github.com/PaulWieland/ratgdo/assets/4663918/1c3f8620-6144-4c1f-8bd4-03069b23c045)
![IMG_6016](https://github.com/PaulWieland/ratgdo/assets/4663918/97e833e6-6bb9-48ef-8a92-bbb19ac04915)

**Comment by rafaelmathieu** [comment]
Perfect thanks for the update

**Comment by PaulWieland** [comment]
I realized I made a mistake in my previous post... **drain goes to RPM2, not RPM1**. My board is running an unreleased firmware and it stopped working when I flashed it to 2.1 ;)
