### ISSUE TITLE
v2.0 - Controlling the light via MQTT causes erroneous obstruction detected events most of the time

### ISSUE THREAD

**Issue by Automayted** [PaulWieland/ratgdo#34]
When publishing `on` or `off` to `/command/light`, I get an immediate sequence of `obstructed` and `clear` payloads received from `/status/obstruction`. When not toggling the light, the are no erroneous obstruction events published. Oddly, this doesn't occur at all times but is rather consistent (90%+) on both my openers. 

Maybe worth noting, using the LCD configuration panel on my openers, I've disabled light activation via the PIR motion detectors built into the control panel as well as disabled light activation from the obstruction sensors.

I'm running the latest code and my boards are USB powered, connected to two Chamberlain B970 openers (50DCBR5 mainboards).

Let me know what other info I can provide to assist in troubleshooting.

Thanks!

**Comment by PaulWieland** [comment]
Does it do this every single time or only when waking the GDO from sleep/power save mode?

**Comment by PaulWieland** [comment]
What about when you toggle the light using the wall mounted button?

**Comment by iceman73** [comment]
I have the same issue and I can confirm when I toggle the Light from the wall mounted switch I also see the Obstruction detected and cleared message just like using the MQTT command for the light.

**Comment by Automayted** [comment]
v2.1a seems to have resolved the issue on both my openers. Thanks!

Will future releases be available to download, so I can flash OTA vs directly-connected serial?

**Comment by PaulWieland** [comment]
Considering this fixed in 2.1a. Still working on an issue with availability before releasing 2.1.

**Comment by Automayted** [comment]
v2.1a resolved this for me, but the issue has returned with slightly different behavior in v2.1b. In v2.1b, every single light on command for both of my openers results in false Obstruction Detected and Obstruction Cleared status messages. Light off commands do not result in any erroneous messages, only light on.

![Screen Shot 2023-05-08 at 1 14 29 PM](https://user-images.githubusercontent.com/66129101/236900360-9f737ccc-8546-4b66-992d-f92db4b8ab95.png)

**Comment by PaulWieland** [comment]
this shouldn't be possible since the motion detection code is identical between the two. but just in case i put 2.1a & b back and published 2.1c (same as 2.1b + support for motion detection hardware) if you want to try and compare.

**Comment by Automayted** [comment]
Checking back in on this. Is there any other testing or log captures that I can provide to assist with resolution?

**Comment by PaulWieland** [comment]
It could be some sort of noise or interference with the obstruction signal on your model opener that occurs when the light relay is tripped. It’s hard to know for sure without a scope or signal analyzer

**Comment by Automayted** [comment]
Thanks, Paul. That makes sense, feel free to close this. 

If I find time to drag my scope out to the garage to collect data, I'll reopen the issue.

**Comment by PaulWieland** [comment]
We can leave open, i dont think you are the only one. I'm just unable to reproduce it. The fact you have a scope means we have the means to solve this... so when you have time, capture some data and share it here. 

Hopefully you have a two channel scope.

Connect ch1 to red ctrl line. set a trigger on that channel so it trips when you toggle the light.
Connect ch2 to black obs line.
Toggle the light and see what comes out on ch2.

**Comment by iceman73** [comment]
With2.1 I still get the triggered Obstruction when changing the light as well.

**Comment by Automayted** [comment]
@iceman73, is this also somewhat sporadic for you, or is it consistent for all light on/off commands?

**Comment by iceman73** [comment]
Consistent
![image](https://github.com/PaulWieland/ratgdo/assets/2061265/38efaa96-236d-4c55-824a-dc6b2f82cd39)

**Comment by PaulWieland** [comment]
There are two possibilities I can think of:

* there is noise being picked up by the shield.
* the GDO itself is interrupting the obs signal when the light bulb relay is toggled.

Both issues can be solved in software but I need some data logging from a scope or signal analyzer to know exactly how to deal with it.

On my opener, the light is turned on as soon as you break the beam (so if the door was left open and the light has shut off, then you walk through the door way the light turns on). That means I cant just skip sending obstruction messages when the light is toggled because it would interfere with a common real world scenario where the obstruction state changes with the light state.

**Comment by Automayted** [comment]
I'll should have time this weekend to bring my scope out to the garage and capture data as you requested [here](https://github.com/PaulWieland/ratgdo/issues/34#issuecomment-1554997031).

Thanks for the awesome support, Paul!

**Comment by iceman73** [comment]
> There are two possibilities I can think of:
> 
> * there is noise being picked up by the shield.
> * the GDO itself is interrupting the obs signal when the light bulb relay is toggled.
> 
> Both issues can be solved in software but I need some data logging from a scope or signal analyzer to know exactly how to deal with it.
> 
> On my opener, the light is turned on as soon as you break the beam (so if the door was left open and the light has shut off, then you walk through the door way the light turns on). That means I cant just skip sending obstruction messages when the light is toggled because it would interfere with a common real world scenario where the obstruction state changes with the light state.

This is how my system works as well

**Comment by Automayted** [comment]
I migrated to https://github.com/ESPHome-RATGDO/esphome-ratgdo and I'm unable to duplicate this issue since. Closing.

**Comment by DuelCoreF18** [comment]
@Automayted Are you running the Ratgdo board just fine via EspHome? I also have 2x Chamberlain B970 openers manufactured 10/02/20. Do I need to check the mainboard to ensure compatibility and if so any notes on how/what/where I'm looking?

**Comment by PaulWieland** [comment]
If you have an overhead mounted security + 2.0 opener (yellow learn button), then it's supported. All chamberlain openers made since somewhere around 2015 are security + 2.0.

There was an issue with some jackshaft mounted openers using the older wireline protocol that is being addressed.

**Comment by Automayted** [comment]
@DuelCoreF18, Ratgdo V2 boards with an ESP8266 running ESPHome has been absolutely flawless with my two B970 openers. I can't recommend this solution enough.

**Comment by DuelCoreF18** [comment]
> @DuelCoreF18, Ratgdo V2 boards with an ESP8266 running ESPHome has been absolutely flawless with my two B970 openers. I can't recommend this solution enough.

Thanks for the feedback!
