### ISSUE TITLE
ratgdo square order

### ISSUE THREAD

**Issue by dovy6** [PaulWieland/ratgdo#36]
I purchased one of your shields and I'm wondering if you have any idea when it may ship? I tried to respond to the email receipt but heard nothing back, so I'm reaching out here. 
Please advise.
Thanks so much for the work you do.

**Comment by PaulWieland** [comment]
Hi,My reply might have gone to your spam folder. Sent from my iPhoneOn Apr 9, 2023, at 12:10 AM, dovy6 ***@***.***> wrote:﻿
I purchased one of your shields and I'm wondering if you have any idea when it may ship? I tried to respond to the email receipt but heard nothing back, so I'm reaching out here.
Please advise.
Thanks so much for the work you do.

**Comment by dovy6** [comment]
Thanks so much, it did indeed go to spam. Awesome to hear, thanks again for putting this together. Have a great day!
