### ISSUE TITLE
support different reed switch configurations

### ISSUE THREAD

**Issue by kirsch33** [PaulWieland/ratgdo#40]
so after finally getting the wiring corrected (per https://github.com/PaulWieland/ratgdo/issues/39) i am still having issues. Ive figured out its because I have my reed switch set to be OPEN when the door is closed, which is opposite from how the door status loop is expecting things to be when reading the digital pin status of RPM1.

I really want to keep this configuration because it gives me accurate readings because I can place the sensor very nearby the magnet. theres no easy option for me to do this when the door is in the open position.

can you add an option in the web server configuration settings for supporting my configuration? right now it will always read as reed_open which makes it pretty unusable

**Comment by kirsch33** [comment]
@PaulWieland  or I could fork this repo and make some very simple changes to accommodate my setup. If I do so and compile from source, is there anything special about flashing the firmware that I need to know? Worried about the rolling codes and such if I were to attempt this

**Comment by PaulWieland** [comment]
You can recompile it but that seems kind of silly for this. `reed_open` means the reed switch is open circuit. `reed_closed` means the magnet is near and closing the circuit.

A simple Home Assistant automation can be triggered on `reed_open` or `reed_closed` and in turn send another mqtt message to update the door status.
