### ISSUE TITLE
On Version 2.0, can we solder the 3.3v pin to the garage 3.3 output to eliminate needing a USB power?

### ISSUE THREAD

**Issue by iceman73** [PaulWieland/ratgdo#42]
Is Ground also required or does the black cable on the Garage Door Sensors act as a ground?

**Comment by PaulWieland** [comment]
The white terminal on the GDO which connects to ratgdo is ground.

Therefore you only need a single additional wire if you wish to tap a 3.3v power source on the GDO's logic board.
