### ISSUE TITLE
Sharing Board Schematics

### ISSUE THREAD

**Issue by shbatm** [PaulWieland/ratgdo#43]
Thanks for the project. I just received my V2.0 board, but I was looking at possibly including this in an update to my existing multisensor board I have in my garage, would it be possible for you to share the board schematics / BOM / EAGLE files?

I recognize you are selling these, but since the code is open source, I thought I'd ask.

**Comment by Marus** [comment]
Would also be interested in this as I wouldn’t mind doing a custom board with some additional parts.

**Comment by dorkage** [comment]
I also would be very interesting in schematics.

**Comment by tylermeredyk** [comment]
just received mine works great. board is a bit big. id like to make a pcb with jst connectors. +1 for schematics

**Comment by fgonza2** [comment]
did they shared the schematics somewhere?

**Comment by tylermeredyk** [comment]
Doesn’t seem like he wants to give them out… As far as I got. 
![IMG_7295](https://github.com/PaulWieland/ratgdo/assets/11326423/4a8c6f39-4003-492e-ac70-ba1053f71074)

**Comment by brad07x** [comment]
Was just going to post to see if there was any info out there on how to hook up the obst/ctrl lines as I'd like to hack something together until my backordered unit arrives; my setup broke again this week with the breaking API changes and related issues with pymyq.

**Comment by ripnet** [comment]
Hello. Were the schematics ever released? Everything is on backorder or else I'd order a few. I am also interested in creating a board with an onboard 3.3v regulator.
