### ISSUE TITLE
Unable to open/shut/toggle light after update

### ISSUE THREAD

**Issue by Trinitrogen** [PaulWieland/ratgdo#46]
Recently received the board, and flashed it with 2.0 and had stability issues. Device would show as unavailable in Home Assistant after a certain amount of time. Noticed a [similar issue was reported](https://github.com/PaulWieland/ratgdo/issues/37), and I was able to replicate the behavior by rebooting my AP this morning.

I reflashed  to 2.1c, opting to erase the device without thinking about it. After installing and rebooting, its available within Home Assistant for me. I'm monitoring the MQTT and see all the messages come through. But when I send the open and close messages via home assistant, the door doesn't open and shut.

[Here is the serial log](https://github.com/PaulWieland/ratgdo/files/11444220/ratgdo.txt). I restart the device, then open an close the garage from my liftmaster wall switch. I've noticed the light is blinking on the wall switch and requires me to press 2 or 3 times. Then I try to open via HomeAssistant.

I think maybe its related to neglecting to set_code_counter after erasing the device. Is there a way to confirm this is my issue, and a way to fix?

**Comment by PaulWieland** [comment]
Did you erase the ESP when you flashed the new version?

**Comment by Trinitrogen** [comment]
Correct. More specifically, I mistakenly reflashed the 2.0 version on again, selecting to erase ESP. Shortly after, I realized I installed the same version and went back and flashed to 2.1c _without_ erasing.

**Comment by PaulWieland** [comment]
From the flasher page:
> Note: Erase Device will erase your configuration and last used rolling code counter. Before you use this option, open the Logs & Console, send a command to your opener and take note of the last used counter. Then after flashing, send an mqtt set_code_counter command to restore the counter value and then sync with the opener. [See docs](https://paulwieland.github.io/ratgdo/01_features.html).

**Comment by Trinitrogen** [comment]
Will try. Do I need to reflash and erase first? Or just use what I have and do a set_code_counter followed by a sync?

**Comment by PaulWieland** [comment]
you do not need to reflash unless you want to change the firmware version. you should never need to erase, unless you have a very specific reason to do so.

**Comment by Trinitrogen** [comment]
Thank you, I set_code_counter to 500 followed by sync and everything worked!
