### ISSUE TITLE
Feature Request: Add OTA Firmware Update Functionality to the Web-UI

### ISSUE THREAD

**Issue by Automayted** [PaulWieland/ratgdo#55]
As discussed [here](https://github.com/PaulWieland/ratgdo/issues/48), currently the only way to update device firmware OTA is via [espota.py](https://github.com/esp8266/Arduino/blob/master/tools/espota.py). It would be beneficial to all users if ratgdo could incorporate an OTA update feature into the web-UI, similar to how Tasmota, WLED, and many other ESP-based projects have done.

For reference:
[Tasmota](https://github.com/arendst/Tasmota)
![image](https://github.com/PaulWieland/ratgdo/assets/66129101/9de3b1a3-d61b-4831-9dda-f496a04e517c)

[WLED](https://github.com/Aircoookie/WLED) 
![image](https://github.com/PaulWieland/ratgdo/assets/66129101/749a4cb2-6978-4e2c-83e4-c478f4e7891d)

**Comment by PaulWieland** [comment]
the Arduino OTA that is supported by ratgdo via arduino bootstrapper requires a client to authenticate and push the firmware to the ESP. I don't think thats possible to do from a browser application.

It would be possible to have the ESP8266 download the firmware from the internet and update itself after receiving a specific mqtt command or web UI button click.

**Comment by Automayted** [comment]
https://github.com/ESPHome-RATGDO/esphome-ratgdo added this functionality. Closing.
