### ISSUE TITLE
Polling Intervals?

### ISSUE THREAD

**Issue by dawgbonez** [PaulWieland/ratgdo#59]
Let me preface, with that I'm a Noob... SO excuse me.

What's the polling mechanism with the D1 unit?
I've created, what I "thought" should be a solid automation.... BUT turning off the light is being a bit troublesome(hit/miss)???

It seems that there is a 5 minute polling(timeout) built in??? Can I change that?

**Comment by PaulWieland** [comment]
There is no polling interval. The gdo reports the light state. The light is turned on automatically on some units when the door is opened or the obstruction sensor is interrupted while the door is open. It then shuts off automatically after a certain period of time.
