### ISSUE TITLE
LiftMaster 8160W - No Actions/No Responses

### ISSUE THREAD

**Issue by WinterPhoenix** [PaulWieland/ratgdo#67]
Hi everyone,

I'll just do a list of my setup since it's a more readable format:
- Wemos D1 Mini
- Ratgdo Shield v2.0
- Ratgdo Firmware v2.1
- MQTT Broker: Mosquito inside of Home Assistant
- Garage Door Opener: LiftMaster 8160W

ratgdo shows up in Home Assistant, but always reports:
- Obstruction: Detected
- Light: Unknown
- Cover: Unknown

Furthermore, trying to do any actions just doesn't work. I tried `set_code_counter` followed by `sync`, with a value of `500` then a value of `1000`, but no dice.

I've looked through several issues now trying to figure this out, including #54, which seemed promising until I tried shorting Ctrl and Ground and it did absolutely nothing. Also, hitting the wall door opener does open the door, but there's nothing reported in ratgdo's logs.

- Voltage across Ctrl/Gnd at the shield: ~10.95V
- Voltage across Obst/Gnd at the shield: ~5.90V

Here are some pics:
![2023-06-23 20 25 30](https://github.com/PaulWieland/ratgdo/assets/2799393/bdde805e-b9c5-4ff0-b215-923e1aa11323)
![2023-06-23 20 25 39](https://github.com/PaulWieland/ratgdo/assets/2799393/11f53e69-9167-4a74-b7c3-7612c8df32ee)

Here are the logs:
[esp-web-tools-logs.txt](https://github.com/PaulWieland/ratgdo/files/11854001/esp-web-tools-logs.txt)

Any help is appreciated; thanks for the great project!

**Edit:** Something I noticed when getting the logs, hitting Download Logs resets the device for some reason. Also, there's an entry for a Dry Contact toggle, but I hadn't pressed anything?

**Comment by PaulWieland** [comment]
It’s not wired right. Theres a silkscreen label for all of the terminals.

**Comment by WinterPhoenix** [comment]
PFFFT. I had it flipped, nice. Rewired it, everything works now. Sorry about that!
