### ISSUE TITLE
Not working on chamberlain B970T (05DCTWF)

### ISSUE THREAD

**Issue by mkaatman** [PaulWieland/ratgdo#71]
Chamberlain B970T

https://www.amazon.com/gp/product/B075CQ86ZV/

Hopefully this is simple user error on my part and someone can guide me.

I used three wago connectors. Red for red, yellow for white, black for black.

The motion detection is working. When I hook up the red wire from the ratgdo to the wago it cuts power to the wall mount control.

![image](https://github.com/PaulWieland/ratgdo/assets/275547/5bffff5a-8a21-41ac-a357-32ccbb4f1894)
![image](https://github.com/PaulWieland/ratgdo/assets/275547/ee5ef7d9-53d3-46a1-b4a9-06926c12fe47)

Thank you for any assistance.

**Comment by mkaatman** [comment]
A friend has informed me that splicing it like this won't work. I'll remove the wagos tomorrow and see what happens

**Comment by PaulWieland** [comment]
Wiring like that should be fine. Have you flashed the firmware?

**Comment by PaulWieland** [comment]
Also does it still short to ground (cut power) if you remove the d1 mini from the shield?

**Comment by mkaatman** [comment]
> Wiring like that should be fine. Have you flashed the firmware?

I have. It's running 2.1

> Also does it still short to ground (cut power) if you remove the d1 mini from the shield?

I'll try that today and report back.

**Comment by mkaatman** [comment]
> Also does it still short to ground (cut power) if you remove the d1 mini from the shield?

Yes, with the d1 removed, as soon as I power the shield the wall switch loses power.

**Comment by PaulWieland** [comment]
And can ratgdo control the door at all?

**Comment by mkaatman** [comment]
No it can't. The led blinks when I send commands.

**Comment by PaulWieland** [comment]
What was your order number?

**Comment by mkaatman** [comment]
877677197

**Comment by mkaatman** [comment]
Closing as id10t error. I pulled the wagos out and restriped the garage wires and everything is working now.
