### ISSUE TITLE
Automatically generated device name should not have an underscore

### ISSUE THREAD

**Issue by pfak** [PaulWieland/ratgdo#75]
DHCP will (and does, in a lot of cases) set the hostname provided by the DHCP lease request. RFC 2132 requires a valid hostname (https://www.rfc-editor.org/rfc/rfc2132.html#section-3.14)

That RFC references RFC1035 for a list of valid hostnames:

https://www.rfc-editor.org/rfc/rfc1035#section-2.3.1             

Which does not include an underscore as valid hostname. For example, OpenWrt will not let you set a static lease with the default device name used by ratgdo.

**Comment by PaulWieland** [comment]
This is actually an issue with Arduino_BootStrapper https://github.com/sblantipodi/arduino_bootstrapper/blob/37d53938979783f54eefb626c6827d45fa6e1d75/src/WifiManager.cpp#L694

I will change it in the fork used by ratgdo for the next release.
