### ISSUE TITLE
Device not responding / Can't open web ui

### ISSUE THREAD

**Issue by underqualifieditguy** [PaulWieland/ratgdo#78]
About three days ago, my garage door device went unreachable in Home Assistant / HomeKit. It's on a static IP and responding to ping, confirmed it's the right device by unplugging the power and the ping stops (I didn't see a MAC address printed on it). The web UI does not load, it definitely is still enabled because I've been able to manage it since I flashed it and wired it up. Any thoughts? Should I try reflashing it?

**Comment by PaulWieland** [comment]
That’s really odd. Try reflashing. Don’t erase it or you will lose the stored code counter.

**Comment by underqualifieditguy** [comment]
> That’s really odd. Try reflashing. Don’t erase it or you will lose the stored code counter. 

I'll give this a shot this evening and report back.

**Comment by underqualifieditguy** [comment]
I re-flashed it, still not working. All I see in the logs are MQTT attempts repeating over and over. I know that MQTT is working because I have lots of other devices communicating on it and they aren't facing any issues.

**Comment by underqualifieditguy** [comment]
OK let's hold up a sec maybe I do have issues with MQTT causing this. I'll get back to you.

**Comment by underqualifieditguy** [comment]
This was totally of my own doing, I accidentally overwrote my MQTT auth file, sorry to disturb!
