### ISSUE TITLE
How to find out RPM1 and rmp2 on other Boards

### ISSUE THREAD

**Issue by Bjoern3003** [PaulWieland/ratgdo#8]
Hi,

interesting Project.

Did you know, if there is a way to find out rpm1 and rpm2 on other boards than yours?

I have door opener ML1040EV from CHamberlain with yellow button and want to come back from cloud service.

**Comment by PaulWieland** [comment]
Have a look at the module in your opener and check to see if it has a 6 wire harness connecting it to the logic board. 

This is what the module looks like: https://www.chamberlain.com/ac-travel-module-kit/p/041D7742-7

**Comment by Bjoern3003** [comment]
I have took 2 pictures. Not looking like that. 😔

![IMG_20220904_170516](https://user-images.githubusercontent.com/13675579/188320378-a943acc4-259b-47ad-a806-47f5c6207ba0.jpg)
![IMG_20220904_170516](https://user-images.githubusercontent.com/13675579/188320394-717b4f4e-cb5d-4524-873b-e7f6b089d004.jpg)

**Comment by Scott--R** [comment]
Please note that if you're not in North America your opener most likely responds to simple contact closure commands. Your ML1040EV would be one of them. If you short the control terminals together you will most likely find that it works just fine. The encrypted technology as far as I know is only found in North American openers.

**Comment by Bjoern3003** [comment]
Very sad ☹️ the project sounds interesting. But the "without soldering method" is not that, what I am looking for.

**Comment by Scott--R** [comment]
I think perhaps you misunderstood @Bjoern3003 I meant that you should be able to control your garage door opener without requiring the commands from RATGDO. You may still be able to tap the RPM signals somewhere, but I just wanted you to know that in my experience, openers like yours can be operated by simple contact closure, making them much easier to work with.

**Comment by Bjoern3003** [comment]
Sure, this is possible, but then I did not get the actual position back as response.

Maybe we can find more peaple to extend this project for other models.

**Comment by jbbjarnason** [comment]
I have a similar case, with Chamberlain ML810EV. 
![PXL_20220917_184355675](https://user-images.githubusercontent.com/15651464/190872165-d17a48a7-6ca8-4afe-ba32-f2c71cbf5056.jpg)

@Bjoern3003 Have you made any progress?

**Comment by Bjoern3003** [comment]
Not really. But I am still interested in any solution. Your model looks same like my.

**Comment by jbbjarnason** [comment]
@Bjoern3003 have you been able to connect it in a soldreless setup? I can't find any information on the pinout on this device.

**Comment by Bjoern3003** [comment]
I have to disconnect the complete pcb for that. Sure I can. But I think I am not able to find out the correct pins for rpm1 and 2. 🙁

**Comment by PaulWieland** [comment]
The pins of the rotary encoder (travel module) for my opener were labeled. Check the pcb and see. If not post a picture of it

**Comment by Bjoern3003** [comment]
On the rotary side or pcb side? On pcb is it not labeled and or travel module does only have 3 pins.

**Comment by PaulWieland** [comment]
On the rotary encoder side. If it only has 3 pins I don’t think it can be a rotary encoder. Do you have a multimeter to check the pins for voltage?

**Comment by Bjoern3003** [comment]
Sure I have. Do I have to check during up and down running?

**Comment by PaulWieland** [comment]
Can anyone find a description of what all the push terminals are for on the back of the opener? This model is nothing like the openers sold in the USA.

**Comment by Scott--R** [comment]
So these are basically the Merlin openers. If you look up Merlin MT100EVO you'll find more details, but I've attached a screenshot of the terminals and put my own descriptions below:

0 serial communications port

1 and 2 are the wall control (similar to USA), but the strange thing is that even though it is a MyQ opener my experience has been that these types of openers (with push terminals that look like this) are directly compatible with contact closure on 1 and 2 and don't require anything special to control them. They respond to both types of inputs and the Merlin openers even ship with a green pushbutton that inserts right into these terminals so you can press that button on the opener directly to operate it.

2 and 3 are the obstruction sensors (same as USA)

4 and 5 have a jumper. You remove that jumper and insert wires for something called a "door connection"  or "door in door" feature.

6 and 7 are for a "flashing light" feature. Generally just leave empty.

![Merlin](https://user-images.githubusercontent.com/10068647/191034218-f0901cba-c059-43f8-af48-b4b2291cb714.png)

**Comment by PaulWieland** [comment]
Version 2.0 of the board eliminates the need for soldering.

Version 1.0 boards are incompatible with 2.0 firmware unless you solder a transistor to the board. I will send anyone with a 1.0 board a free transistor if they email me their order number. Instructions for the mod are forthcoming.

That being said, i don't think the door openers mentioned in this thread are security + 2.0 openers. I see no mention of it in the manual. They seem to support traditional dry contacts so theres no real need for ratgdo.

**Comment by Bjoern3003** [comment]
New Try... its working with Version 2.0. I have it tried with the latest version of https://github.com/PaulWieland/ratgdo/tree/2.0-secplus1.0 and Secure 2.0

Red to Green (Pin 0)
White to White (Pin2)
Grey to Grey (Pin 3)
