### ISSUE TITLE
Compatible with Chamberlain 045ACT board?

### ISSUE THREAD

**Issue by nicholas-ochoa** [PaulWieland/ratgdo#81]
I've got a Chamberlain garage door opener made in 2017 that has a `045ACT` board. It appears to be a security 2.0 opener as far as I can tell, the included remote controls are part # `953ESTD` which appears to be identical or at least compatible with the Liftmaster 893LM remote - which [this document](https://www.windsordoor.com/assets/uploads/modules/accessory-compatibility-chart-91817-82926.pdf) indicates is strictly a Security 2.0 device. 

I'm not sure of the model number of the door opener itself, I can't see that anywhere on the device.

Any chance this is compatible with ratgdo?

**Comment by PaulWieland** [comment]
Yes it is compatible with ratgdo.
