### ISSUE TITLE
CLI to Flash the ESP Board? 

### ISSUE THREAD

**Issue by jacksnodgrass** [PaulWieland/ratgdo#88]
I run Linux. I have Chrome. I connected my esp board and I see: 
```

[Wed Sep  6 11:03:12 2023] usb 1-9.1.1: new full-speed USB device number 23 using xhci_hcd
[Wed Sep  6 11:03:12 2023] usb 1-9.1.1: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice= 2.54
[Wed Sep  6 11:03:12 2023] usb 1-9.1.1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[Wed Sep  6 11:03:12 2023] usb 1-9.1.1: Product: USB2.0-Ser!
[Wed Sep  6 11:03:12 2023] ch341 1-9.1.1:1.0: ch341-uart converter detected
[Wed Sep  6 11:03:12 2023] ch341-uart ttyUSB0: break control not supported, using simulated break
[Wed Sep  6 11:03:12 2023] usb 1-9.1.1: ch341-uart converter now attached to ttyUSB0
```
I go to: https://paulwieland.github.io/ratgdo/flash.html and try and flash my board on ttyUSB0 I get: 

paulwieland.github.io says: 
**Failed to execute 'open' on 'SerialPort': Failed to open serial port.**

I successfully installed:  esp-flasher - a python script that I think could flash this board..... any way / instructions to use that.  I don't have a windows box easily accessible to flash from....  what are my Linux options?

**Comment by PaulWieland** [comment]
It's possible that chrome can't access the serial ports under linux, but I've never tried it because I've never used linux with a GUI. Make sure nothing else on your system has the serial port open as that would block chrome from being able to open it.

Something like this should work to flash from the CLI:  `esptool.py -b 115200 write_flash 0 /path/to/firmware.bin`

docs: https://docs.espressif.com/projects/esptool/en/latest/esp8266/esptool/basic-commands.html

**Comment by jacksnodgrass** [comment]
It might be a permission thing.... you run chrome as a normal user... but accessing things like the USB ports have to be done as ROOT....  I can figure out the **esptool.py -b 115200 write_flash 0** part.... where do I find the 
`firmware.bin`
that needs to be flashed?

**Comment by PaulWieland** [comment]
You can download the binaries from the repo. Assuming you want the latest with wifi:

https://github.com/PaulWieland/ratgdo/blob/main/docs/flasher/ratgdo_esp8266_v2.1.bin

**Comment by jacksnodgrass** [comment]
OK.  You can close this.... maybe document it someplace... maybe.... 
For Linux, I did: 
`pip install esp-flasher`
then I could fire up 
`esp_flasher`
which brings up a GUI. I was able to flash the .bin file I downloaded from: 
`https://github.com/PaulWieland/ratgdo/blob/main/docs/flasher/ratgdo_esp8266_v2.1.bin`
and was able to flash the board.  

I was then able to access the ratgdo AP on it's 192.x.x.x. address and finish the configuration.
