### ISSUE TITLE
Non-standard Usage info request. 

### ISSUE THREAD

**Issue by jacksnodgrass** [PaulWieland/ratgdo#89]
I know that the preferred way to use the ratgdo and the esp8266 board is with MQTT  and / or home assistant....  but are there any API / behind the scenes ways to access the ratgdo board over Wi-Fi?  

I mean... is there any way to do something like: 

`http://<ratgdo ip>/command/light/on`
or 
`http://<ratgdo ip>/command/light/off`

Are there any groups / people that use the ratgdo board with things like a Raspberry Pi? 

Just seeing what all of the options are. 

I have 2 garage doors ( bought 2 RATGDO boards ) and a driveway gate that I control with a Raspberry Pi and a relay board.   I also have a HD Camera view of my driveway gate and I have a HD Camera view of the interior of my garage. My end-game is to have one 'controller' control my two garage doors and my driveway gate so that I can control them from one app and see output from the cameras. I am thinking that I might just want to connect the 2 RATGDO board and my relay to a single Pi and control them all from the one device... but I am not 100% sure that will work or that's what I should do.... just exploring my options. 

Thanks

**Comment by PaulWieland** [comment]
mqtt is a better technology for devices like ratgdo, temp sensors, motion sensors, or any other type of small microcontroller sensor that you want to deploy. It deals with poor signal strength, retries and preserving states. REST apis are stateless and usually imo directional (unless you use web sockets). REST presents a large set of challenges that you have to deal with to get a reliable solution which is one of the big reasons why MQTT was invented. 

Install docker on your pi and run mosquitto (or any of the dozens of available brokers). Home assistant can also be run in docker. 

Install the home assistant app on your mobile device and get all the stuff you are looking for in one easy to manage stack.
