### ISSUE TITLE
Can't access webui (could before)

### ISSUE THREAD

**Issue by monkey-of-the-hill** [PaulWieland/ratgdo#96]
Can't access Web UI of previously working/configured device. I've reflashed it and still no access. Can connect to logs over USB and it shows it's connected to WiFi, router shows it connected but no UI or ping.

**Comment by PaulWieland** [comment]
See [Disable OTA & Web Server Config Access](https://paulwieland.github.io/ratgdo/02_configuration.html). To reset it you have to fully erase the flash on the D1 Mini when you install the firmware.

If you have been using ratgdo with your opener, make sure you get the last rolling code and then use [set_code_counter](https://paulwieland.github.io/ratgdo/01_features.html) to set that value after you erase and reconfigure.

**Comment by monkey-of-the-hill** [comment]
Never mind. Network issues. I'm a dope. Works fine. False alarm.
