### ISSUE TITLE
Collision detected message; unit installed

### ISSUE THREAD

**Issue by greggitter** [PaulWieland/ratgdo#98]
Hi, I looked through all the issues and saw one related to this message where someone had not yet installed the unit and was getting this message, but I have the unit installed.

Soldered the D1 mini to the shield and flashed the board using chrome.  Adopted via ESPhome in HA, it compiled and uploaded.  Connected red/white/black to the GDO.  System-wise, I can ping the board and get diagnostics but it seemingly fails to communicate with my GDO.  I'm wondering if my head unit is not compatible.  These two openers were purchased in 2014 (one has a battery backup and [this one does not](https://www.amazon.com/gp/product/B00APL6Q0W/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)) and the only mention of 2.0+ security in the manual is this:  "This garage door opener is compatible with MyQ® and Security+ 2.0® accessories."

Assumption is "should" be compatible (?).  So I am wondering if there is anything else I can test to see where the problem is.  I've verified a dozen times the wires are connected correctly...even tried reversing white and black and that prevents the unit from booting.

Thanks!

**Comment by PaulWieland** [comment]
Please post a picture of your wiring as well as the model number of your wall control panel.

**Comment by greggitter** [comment]
Thanks for the quick reply.  Initially the wiring was basically using the wire clamps on the GDO itself but I convinced myself I had a connection issue and wanted to verify using pigtails.


![2](https://github.com/PaulWieland/ratgdo/assets/68356047/96bb059e-bc06-43e1-9b30-a7f0511ee22c)
![IMG_0809 (Large)](https://github.com/PaulWieland/ratgdo/assets/68356047/01f6d9fd-e724-46ad-9688-8fc91b88533f)
![IMG_0811 (Large)](https://github.com/PaulWieland/ratgdo/assets/68356047/c665480b-22db-46a0-9eae-8df4efd0031b)

**Comment by PaulWieland** [comment]
The wires are connected to the wrong terminals on the shield. Please look at the terminal labels on the backside where the QR code is.

**Comment by greggitter** [comment]
Well that was easy.  I didn't see the small writing and was referring to wiring diagram and because I could see the antenna on the D1, I assumed I was looking from top down.  Thanks so much!  :)
